"""Regenerate backend/requirements.lock.txt from backend/requirements.txt.

HARDENING_PLAN.md finding P2-L9: run this after editing requirements.txt so
the hash-pinned lock (every transitive dependency, not just the direct pins)
stays in sync. Needs `uv` (``pip install uv``; already in requirements-dev.txt).

Usage: python -m backend.relock_requirements
"""

import re
import subprocess
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent
REQUIREMENTS = BACKEND_DIR / "requirements.txt"
CONSTRAINTS = BACKEND_DIR / "requirements.constraints.txt"
LOCK_FILE = BACKEND_DIR / "requirements.lock.txt"

HEADER = """\
# HARDENING_PLAN.md finding P2-L9: hash-pinned lock of every transitive
# runtime dependency (not just the direct pins in requirements.txt), so a
# build installs byte-identical wheels every time instead of resolving
# open ranges (Starlette, resemblyzer's `typing` and `webrtcvad>=2.0.10`)
# at build time.
#
# torch is deliberately NOT in this file. It only ships a CUDA build on
# the default PyPI index; the CPU build backend/Dockerfile installs (see
# TORCH_INDEX_URL) lives on a separate index this file can't mix in
# without pulling torch's ~6 GB of CUDA-only extras (triton, nvidia-*)
# into every regeneration (HARDENING_PLAN.md finding P2-H3). torch's own
# pin stays exact-pinned in requirements.txt and is installed from its own
# index first, unlocked; everything else installs from this file with
# `pip install --require-hashes`.
#
# Regenerated by: python -m backend.relock_requirements
#
# backend/requirements.constraints.txt overrides two resolver footguns
# found while generating this file, see that file's comments.
"""


def _strip_torch_block(text: str) -> str:
    """Drop the ``torch==...`` entry and its continuation/`# via` lines."""
    lines = text.splitlines(keepends=True)
    out = []
    skipping = False
    for line in lines:
        if re.match(r"^torch==", line):
            skipping = True
            continue
        if skipping and re.match(r"^[A-Za-z]", line):
            skipping = False
        if not skipping:
            out.append(line)
    return "".join(out)


def main() -> int:
    # Run with relative filenames from BACKEND_DIR: `uv` mishandles absolute
    # paths containing spaces (this repo's own directory has one), silently
    # truncating the path at the first space and failing with "File not
    # found".
    result = subprocess.run(
        [
            "uv",
            "pip",
            "compile",
            "--generate-hashes",
            "--torch-backend",
            "cpu",
            "-c",
            CONSTRAINTS.name,
            # No --output-file: uv 0.11 treats "-" as a literal filename and
            # drops a stray `backend/-`; the lock text is read from stdout.
            REQUIREMENTS.name,
        ],
        cwd=BACKEND_DIR,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        return result.returncode

    # Drop uv's own autogenerated header (the first two `#` lines) in favor
    # of ours, which documents the torch exclusion.
    compiled = result.stdout
    body_lines = compiled.splitlines(keepends=True)
    body = "".join(line for line in body_lines if not line.startswith("#"))
    body = _strip_torch_block(body)

    LOCK_FILE.write_text(HEADER + body, encoding="utf-8")
    print(f"Wrote {LOCK_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
